proxmox_api_host: 192.168.1.93
proxmox_api_user: "terraform-prov@pve!ansible"
proxmox_node: pve
proxmox_validate_certs: false

proxmox_storage: local-lvm
proxmox_cloud_image_storage: local
proxmox_bridge: vmbr0

ansible_user_name: ansible
ansible_user_public_key: "{{ lookup('file'), lookup('env', 'HOME') + '/.ssh/homelab_ansible.pub' }}"
ansible_private_key_file: "{{ lookup('env', 'HOME') + '/.ssh/homelab_ansible' }}"

