- name: Identify NVIDIA GPU device numbers (https://proxmenux.com/en/guides/nvidia-manual/#:~:text=5%2E%20Configure%20an%20LXC%20container%20to%20use%20the%20GPU)

- name: Create LXC from Debian 13 template or edit LXC config
