apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      nodeSelector: # Schedule only on Pi5 with more resources
        kubernetes.io/hostname: master # Replace with your Pi5 hostname, can also use IP
      containers:
      - name: grafana
        image: grafana/grafana
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: grafana-data
          mountPath: /mnt/grafanadisk # Grafana data directory
      volumes:
      - name: grafana-data
        persistentVolumeClaim:
          claimName: grafana-pvc
