- name: Configure Servarr VM (Docker + Servarr docker compose)
  hosts: servarr
  gather_facts: true

  vars_prompt:
    - name: media_disk
      prompt: "Enter the target media disk device to format and mount (e.g., /dev/sdb)"
      private: false
      default: "/dev/sdb"
    - name: servarr_ui_password
      prompt: "Enter the password for the Servarr UI user"
      private: true
      confirm: true
    - name: sabnzbd_ui_username
      prompt: "Enter the SABnzbd UI username"
      private: false
      default: admin
    - name: sabnzbd_provider_name
      prompt: "Enter a name for the Usenet provider"
      private: false
      default: primary
    - name: sabnzbd_provider_host
      prompt: "Enter the Usenet provider hostname"
      private: false
    - name: sabnzbd_provider_port
      prompt: "Enter the Usenet provider port"
      private: false
      default: "563"
    - name: sabnzbd_provider_username
      prompt: "Enter the Usenet provider username"
      private: true
    - name: sabnzbd_provider_password
      prompt: "Enter the Usenet provider password"
      private: true
      confirm: true
    - name: sabnzbd_provider_connections
      prompt: "Enter the provider's allowed simultaneous connections"
      private: false
      default: "10"

  roles:
    - role: docker
    - role: servarr

  # post_tasks:
