servarr_lxc_idmap_base: 100000
servarr_lxc_template_storage: local
servarr_lxc_storage: local-lvm
servarr_lxc_template: ""
servarr_lxc_bridge: vmbr0
servarr_lxc_gateway: 192.168.1.1
servarr_lxc_nameserver: 192.168.1.1
# Explicit opt-in for existing files; large media libraries can take a while.
servarr_media_repair_ownership: false
servarr_media_uuid: ""
servarr_media_fstype: ext4

sabnzbd_ui_username: admin
sabnzbd_provider_name: primary
sabnzbd_provider_port: 563
sabnzbd_provider_connections: 10
jellyfin_admin_username: admin
jellyfin_admin_password: "{{ servarr_ui_password }}"
jellyfin_nvidia_enabled: true
