# Run with: ansible-playbook -i inventory.yaml playbook.yaml -K




- hosts: all
  vars:
     deb_architecture: {
      "armv6l": "armhf",
      "armv7l": "armhf",
      "aarch64": "arm64",
      "x86_64": "amd64",
      "i386": "i386"
    }

  become: true

  tasks:

  - name: Update and upgrade APT packages
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 3600 # One hour

  - name: Disable swap for current session
    command: swapoff -a

  - name: Disable swap permanently (Find and comment (#) lines containg 'swap' in /etc/fstab)
    shell: sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

  - name: Enable IPv4 packet forwarding
    lineinfile:
      path: /etc/sysctl.d/k8s.conf
      line: 'net.ipv4.ip_forward = 1'
      create: yes

  - name: Add docker's official GPG key
    block:
      - name: Install ca-certificates and curl
        apt:
          name:
            - ca-certificates
            - curl
          state: present

      - name: Create /etc/apt/keyrings directory with appropiate permissions
        file:
          path: /etc/apt/keyrings
          state: directory
          mode: '0755'

      - name: Download Docker GPG key to /etc/apt/keyrings/docker.asc
        get_url:
          url: https://download.docker.com/linux/debian/gpg
          dest: /etc/apt/keyrings/docker.asc
          mode: '0644'

      - name: Add Docker APT repository to sources
        apt_repository:
          repo: deb [arch={{ [ansible_architecture] | map('extract', deb_architecture) | first }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
          filename: docker
          state: present
