# Run with: ansible-playbook -i inventory.yaml playbook.yaml -K

- hosts: all
  become: true
  tasks:

  - name: Update and upgrade APT packages
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 3600 # One hour

  - name: Disable swap for current session
    command: swapoff -a

  - name: Disable swap permanently (Find and comment (#) lines containg 'swap' in /etc/fstab)
    shell: sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

  - name: Enable IPv4 packet forwarding
    lineinfile:
      path: /etc/sysctl.d/k8s.conf
      line: 'net.ipv4.ip_forward = 1'
      create: yes
